name: Pull Request Workflow
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch
        run: |
          branch=$(echo "${GITHUB_HEAD_REF}" | cut -d / -f 3)
          if [ "${branch}" != "DEV" ]; then
            echo "El pull request debe estar en la rama DEV"
            exit 1
          fi

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.0

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Run unit tests
        run: dotnet test

      - name: Check reviewer
        run: |
          owner=$(echo "${GITHUB_ACTOR}" | cut -d / -f 1)
          if [ "${owner}" != "OWNER" ]; then
            echo "Solo los propietarios de la organización pueden aceptar este pull request"
            exit 1
          fi

      - name: Merge pull request
        if: ${{ success }}
        run: |
          git merge --ff-only "${GITHUB_HEAD_REF}"
          git push
