name: .NET 7 Pull Request CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ "${GITHUB_REF}" != "refs/heads/DEV" ]]; then
            echo "Pull request must be on branch DEV"
            exit 1
          fi

      - name: Set up .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.0-preview.1

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Run unit tests
        run: dotnet test

      - name: Check reviewer
        uses: actions/github-checks@v2
        with:
          ref: ${{ github.head_ref }}
          reviewer-type: owner

      - name: Merge pull request if reviewer is an owner
        if: |
          ${{ steps.check-reviewer.outputs.reviewer-type == 'owner' }} &&
          ${{ steps.build.outputs.build-status == 'SUCCESS' }}
        run: |
          echo "Merging pull request"
          git merge --ff-only ${{ github.head_ref }}
